### PR TITLE
Export operation GUI

### PR DESCRIPTION
**Pull request by Budschie**
So, I added an gui for exporting.
I just found that the open folder dialog is a bit confusing for new users as they don't immediatly know what's going on,
so I added an gui with (currently just one entry). I created this gui with the aim to be extensible, so that new gui entries can
be added in the future. For the gui, I used 16 points font size and trajan pro as the font, to match the look of the
rest of the projects gui.

### CODE REVIEW

**Comment by Janne252** [comment]
Hey, I happened to come across this pull request while downloading the tool.

A common .NET approach to get a better "Choose destination folder" dialog is using the `OpenFileDialog` with `CheckFileExists` set to **`false`**:

```cs
SelectFolderDialog = new OpenFileDialog();
SelectFolderDialog.CheckFileExists = false;
SelectFolderDialog.FileName = "Select this folder...";

...

if (SelectFolderDialog.ShowDialog() == true)
{
    var rootPath = Path.GetDirectoryName(SelectFolderDialog.FileName);
}
```

I personally find the `FolderBrowserDialog`'s user experience absolutely horrendous.

**Comment by Budschie** [comment]
OK, thanks. What exactly does that option do?

**Comment by Budschie** [comment]
Nah, to be honest, I do find the folderbrowserdialog better than the way you described above.
Microsoft seemed to integrated it better into windows, I remember that it was really bad before, it just
showed the part that is usually on the left side of the explorer, but Microsoft seemed to integrated it better into windows, and
it now uses the default explorer gui. Don't know if thats just a false memory though.

**Comment by Janne252** [comment]
Matter of opinion, really. If you can get access to the folder browsing dialog similar to in VS Code (open folder), or in Visual Studio (open a local folder), even better! The last time I needed a native folder browsing dialog the best option was to abuse the `OpenFileDialog`. The `FolderBrowserDialog` is super slow because you have to expand every folder until you're in the destination, whereas in the `OpenFileDialog` you you have a larger window to access stickied locations, edit the path on the "address" bar, paste a path from the clipboard, etc. Just like you can do in VS Code or Visual Studio when opening a folder.

**Comment by Janne252** [comment]
Apologies, I assumed the FolderBrowserDialog still looked like this:
image

It actually looks like this now:
image

Which matches what I [tried](https://github.com/VladTheJunior/Resource-Manager/pull/3#issuecomment-712592041) to explain.

**Comment by VladTheJunior** [comment]
Added commits manually

**Comment by Budschie** [comment]
Ok, thanks for using my gui (:
I really apreciate that.

**Pull request closed without merging**
